### ISSUE TITLE
postinst fix for lighttpd.conf

### ISSUE THREAD

**Issue by pocki80** [dabeani/0xFF-BMK-webstatus#7]
not overwrite lighttpd.conf modification/location for Let's Encrypt installation done by install.sh from smokeping-server! make bmk-webstatus and letsencrypt-skript work together

**Comment by dabeani** [comment]
Will work if we create letsencrypt with a own package! 

Then we can create a new file called /etc/lighttpd/conf-enabled/98-letsencrypt.conf with needed exceptions for the webserver, and enable the new config file in the lighttpd.conf with the include function.

**Comment by dabeani** [comment]
with the new setup of version 3.0 we can arrange this with the webserver configuration!

**Comment by pocki80** [comment]
v4.0 merges with letsencrypt scripts on custom lighttpd server
